### ISSUE TITLE
BUG:Both Sign up and Sign in pages not working 

### ISSUE THREAD

**Issue by UtkarshBirla28** [VanshKing30/FoodiesWeb#375] opened 2024-06-25 17:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot (93)](https://github.com/VanshKing30/FoodiesWeb/assets/96072228/69aa5202-8f8f-4f0a-b658-3cdf10d91190)
![Screenshot (92)](https://github.com/VanshKing30/FoodiesWeb/assets/96072228/785355b7-68b7-4768-bb19-1952e61d83be)

Signup taking 40-50 seconds to create an account which is very inefficient 

On sign in page users are not able to loggin

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment] 2024-06-25 23:33
@UtkarshBirla28  it is working

**Comment by UtkarshBirla28** [comment] 2024-06-26 02:36
@nishant0708 yesterday it wasn't 🙂
Let me check again

**Comment by UtkarshBirla28** [comment] 2024-06-26 02:39
@nishant0708 
![Screenshot_2024-06-26-08-08-49-24_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/VanshKing30/FoodiesWeb/assets/96072228/614dafe1-cd4d-4822-95f1-20098435d819)
Seeeee

**Comment by nishant0708** [comment] 2024-06-26 03:13
Yeah but I have solved this in my pr it will work fine as soon as he will merge any of my pr

**Comment by UtkarshBirla28** [comment] 2024-06-26 03:32
> Yeah but I have solved this in my pr it will work fine as soon as he will merge any of my pr

ohh okok i didn't knew that

**Comment by hustlerZzZ** [comment] 2024-06-26 15:41
No issue i will close this as the issue is fixed now.

**Closed by hustlerZzZ** 2024-06-26 15:41 UTC
